## Leetcode 1572 - Matrix Diagonal Sum
Given a square matrix mat, return the sum of the matrix diagonals.

Only include the sum of all the elements on the primary diagonal and all the elements on the secondary diagonal that are not part of the primary diagonal.



Example 1:
Input: mat = [[1,2,3],
              [4,5,6],
              [7,8,9]]
Output: 25
Explanation: Diagonals sum: 1 + 5 + 9 + 3 + 7 = 25
Notice that element mat[1][1] = 5 is counted only once.
Example 2:

Input: mat = [[1,1,1,1],
              [1,1,1,1],
              [1,1,1,1],
              [1,1,1,1]]
Output: 8
Example 3:

Input: mat = [[5]]
Output: 5

In [1]:
import numpy as np
n=int(input("Enter the no of rows:"))
m=int(input("Enter the no of cols:"))
a=list(map(int,input(f"Enter the array elements of size {n*m}:").split(",")))
b=np.reshape(a,(n,m))
result=0
length=len(b)
for i in range(0,length):
  result+=b[i][i]
  result+=b[length-i-1][i]
if ((n%2)!=0):
  result-=b[length//2][length//2]
print(result)

Enter the no of rows:3
Enter the no of cols:3
Enter the array elements of size 9:1,2,3,4,5,6,7,8,9
25


## Leetcode 50 - Pow(x, n)
Implement pow(x, n), which calculates x raised to the power n (i.e., xn).

Example 1:

Input: x = 2.00000, n = 10
Output: 1024.00000
Example 2:

Input: x = 2.10000, n = 3
Output: 9.26100
Example 3:

Input: x = 2.00000, n = -2
Output: 0.25000
Explanation: 2-2 = 1/22 = 1/4 = 0.25

In [2]:
x=int(input("Enter the value of x:"))
n=int(input("Enter the value of n:"))
def pow(x,n):
  ## Small Problem
  if n==0:
    return 1
  elif n==1:
    return x
  elif (n<0):
    x=1/x
    n=(-n)
    return pow(x,n)
  ## Big Problem
  else:
    ## Divide
    mid=n//2
    ## Conquer
    b=pow(x,mid)
    ## Combine
    result=b*b
    if n%2==0:
     return result
    else:
       return (result*x)
res=pow(x,n)
print(res)

Enter the value of x:2
Enter the value of n:10
1024


## Leetcode 48 - Rotate Image
You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

Example 1:
Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [[7,4,1],[8,5,2],[9,6,3]]

Example 2:
Input: matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
Output: [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]


In [3]:
import numpy as np
n=int(input("Enter the value of n:"))
a=list(map(int,input(f"Enter the array elements of size {n*n}:").split(",")))
b=np.reshape(a,(n,n))
def transpose(matrix,n):
  for i in range(n):
    for j in range(i+1,n):
      b[i][j],b[j][i]=b[j][i],b[i][j]
def swapCols(matrix,n):
  for i in range(n):
    for j in range(0,n//2):
      b[i][j],b[i][n-j-1]=b[i][n-j-1],b[i][j]
transpose(b,n)
swapCols(b,n)
print(b)

Enter the value of n:3
Enter the array elements of size 9:1,2,3,4,5,6,7,8,9
[[7 4 1]
 [8 5 2]
 [9 6 3]]
